// <auto-generated />
using System;
using KWRWebShopAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KWRWebShopAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Våben"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Våbentilbehør"
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Langgade 1",
                            Created = new DateTime(2023, 2, 15, 10, 34, 11, 943, DateTimeKind.Local).AddTicks(1297),
                            FirstName = "Joe",
                            LastName = "Mama",
                            LoginId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Borgmester Christiansens Gade 22",
                            Created = new DateTime(2023, 2, 15, 10, 34, 11, 943, DateTimeKind.Local).AddTicks(1300),
                            FirstName = "Gabe",
                            LastName = "Itch",
                            LoginId = 2
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.ToTable("Login");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            Email = "mail_1@test.dk",
                            Password = "123456789",
                            Type = 0
                        },
                        new
                        {
                            LoginId = 2,
                            Email = "mail_2@test.dk",
                            Password = "123456789",
                            Type = 1
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Created = new DateTime(2023, 2, 15, 10, 34, 11, 943, DateTimeKind.Local).AddTicks(1323),
                            CustomerId = 1,
                            Total = 1898m
                        },
                        new
                        {
                            OrderId = 2,
                            Created = new DateTime(2023, 2, 15, 10, 34, 11, 943, DateTimeKind.Local).AddTicks(1325),
                            CustomerId = 2,
                            Total = 1599m
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Orderline", b =>
                {
                    b.Property<int>("OrderlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderlineId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderlineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLine");

                    b.HasData(
                        new
                        {
                            OrderlineId = 1,
                            Amount = 1,
                            OrderId = 1,
                            Price = 899m,
                            ProductId = 1
                        },
                        new
                        {
                            OrderlineId = 2,
                            Amount = 1,
                            OrderId = 1,
                            Price = 999m,
                            ProductId = 1
                        },
                        new
                        {
                            OrderlineId = 3,
                            Amount = 1,
                            OrderId = 2,
                            Price = 1599m,
                            ProductId = 2
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Toyko Marui",
                            CategoryId = 1,
                            Description = "Airsoft pistol md BlowBack.",
                            Name = "Glock 18",
                            Price = 899m
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "CYMA",
                            CategoryId = 2,
                            Description = "Fuld automatisk assault rifle.",
                            Name = "AK47",
                            Price = 1599m
                        });
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Customer", b =>
                {
                    b.HasOne("KWRWebShopAPI.Database.Entities.Login", "Login")
                        .WithOne("Customer")
                        .HasForeignKey("KWRWebShopAPI.Database.Entities.Customer", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Order", b =>
                {
                    b.HasOne("KWRWebShopAPI.Database.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Orderline", b =>
                {
                    b.HasOne("KWRWebShopAPI.Database.Entities.Order", null)
                        .WithMany("Orderline")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Product", b =>
                {
                    b.HasOne("KWRWebShopAPI.Database.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Login", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KWRWebShopAPI.Database.Entities.Order", b =>
                {
                    b.Navigation("Orderline");
                });
#pragma warning restore 612, 618
        }
    }
}
